name = "osuna-website"
account_id = "96459747319960a0cfc67a31d35e830f"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = "./src/server-entry.ts"

routes = [{ pattern = "osuna.chinhae.cc", custom_domain = true }]

[observability]
enabled = true

[[kv_namespaces]]
binding = "WEBSITE_CACHE"
id = "191b7caebaa942dfbc49383669f7b7cc"
